# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %(app lib config test spec feature)

## Uncomment to clear the screen before every task
# clearing :on

#guard :shell do
#  watch('rakefile.rb') { `rake` }
#end

#notification :growl
notification :gntp, sticky: true, host: '127.0.0.1'

logger level:       :info,
       device:      $stdio


watch(/rakefile\.rb/) { 
	
	puts
	puts '------ rake ------'
	puts `rake `
	puts

	#`c:/tools/notifu/notifu.exe -m "#{output}"`	
}
